<%@ Page Language="C#" Inherits="SP2WebAdmin.Competitions" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head runat="server">
	<title>Competitions</title>
	<link rel="stylesheet" type="text/css" href="media/style.css" />
</head>
<body>
	<form id="form1" runat="server">
		<h1>SAGAPresenter2: Competitions</h1>
			<p><a href="/">Main menu</a></p>
			<asp:ObjectDataSource id="odsCompetitions" runat="server" TypeName="SAGAPresenter.libpresenterd.CompetitionsDataObject"
			 SelectMethod="Select" UpdateMethod="Update" InsertMethod="Insert" DeleteMethod="Delete">
			 	<UpdateParameters>
			 		
			 	</UpdateParameters>
			</asp:ObjectDataSource>
			
			<asp:GridView id="gvCompetitions" runat="server" AutoGenerateColumns="false" DataSourceID="odsCompetitions"
				ShowFooter="true" EmptyDataText="No results!" AllowPaging="true" PageSize="50" Width="100%"
				AllowSorting="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
				DataKeyNames="XMLData"
				>
				<Columns>
					<asp:BoundField
						DataField="Name"
						HeaderText="Name" />
					<asp:BoundField
						DataField="Platforms"
						HeaderText="Platforms"
						ItemStyle-CssClass="consolelogos"
						ControlStyle-CssClass="consolelogos"
						  />
					<asp:BoundField
						DataField="Start"
						HeaderText="Start" />
					<asp:BoundField
						DataField="Finish"
						HeaderText="Finish" />
						
				</Columns>
			
			</asp:GridView>
			
			<h2>Add Competition</h2>
			<asp:DetailsView id="dvCompetitions" runat="server" DataSourceID="odsCompetitions"
				AutoGenerateRows="false" AutoGenerateInsertButton="true" OnModeChanging="dvCompetitions_ModeChanging"
				OnItemInserted="dvCompetitions_ItemInserted"
			>
				<Fields>
					<asp:BoundField
						DataField="Name"
						HeaderText="Name" />
					<asp:BoundField
						DataField="Platforms"
						HeaderText="Platforms"
						ControlStyle-CssClass="consolelogos"
						 />
					<asp:BoundField
						DataField="Start"
						HeaderText="Start" />
					<asp:BoundField
						DataField="Finish"
						HeaderText="Finish" />
				</Fields>
			</asp:DetailsView>
			
			<h2>Platform Icon Codes</h2>
			<table class="platformcodes">
				<tr>
					<% 
						foreach (char x in SAGAPresenter.libpresenterd.CompetitionsDataObject.Alphabet)
							Response.Write("<td>" + x + "</td>");
					%>
				</tr>				
				<tr class="consolelogos">
					<% 
						foreach (char x in SAGAPresenter.libpresenterd.CompetitionsDataObject.Alphabet)
							Response.Write("<td>" + x + "</td>");
					%>
				</tr>
			</table>
	</form>
</body>
</html>